### ISSUE TITLE
Fix launch h2-console

### ISSUE THREAD

**Issue by danilkuznetsov** [ExternSchool/planner#38]
Fix launch h2-console, any request is redirected to "/login" page with "Whitelabel Error Page"

**Comment by mnjl1** [comment]
Suppose nothing to fix. H2-console works fine at another developer Yatsun
Looks like having local problems.

**Comment by mnjl1** [comment]
Fixed the problem by commenting this line in SpringSecurityConfig:
`.and()
//                .formLogin().defaultSuccessUrl("/", true)
//                .loginPage("/login").permitAll().and().logout().permitAll()`

Lets wait for pr from ben with login template

**Comment by mnjl1** [comment]
h2-console works fine
test connection to database has passed successfully
closing pr
